### ISSUE TITLE
Fritzing Files have not been updated.

### ISSUE THREAD

**Issue by dave373** [sparkfun/SunnyBuddy#2]
I was trying to re-configure this board for a 12V SLA and went looking for the layouts so I know which resistor is which. On the readme file, you have the current board, but the Fritzing files haven't been updated. Could someone please do this?  Thanks.

**Comment by loricrotser** [comment]
Apologies for the long reply time - I am just now getting to this! 

Fritzing has been updated for v1.3. Please let us know if you need anything else!

[https://github.com/sparkfun/Fritzing_Parts/blob/master/products/12885_sfe_sunny_buddy_solar_power_v13.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/12885_sfe_sunny_buddy_solar_power_v13.fzpz)
